version: '3'

services:
  py-service:
    build: ./python_api
    volumes:
      - ./python_api:/usr/src/app
    ports:
      - 4001:80

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 4000:80
    depends_on:
      - py-service
